# Dropout Detection and Correction Pipeline with User Decisions
# This example demonstrates a multi-stage pipeline with dropout correction
# Note: Dropout decisions would be applied in the actual processing pipeline
# The GUI focuses on the visual DAG structure

name: "Dropout Correction Pipeline"
version: "1.0"

nodes:
  - node_id: "START"
    stage_name: "START"
    x_position: -450.00
    y_position: 0.00
  - node_id: "node_1"
    stage_name: "Dropout Correct"
    x_position: 300.00
    y_position: 150.00
    overcorrect_extension: 0
    intrafield_only: false
    reverse_field_order: false
    max_replacement_distance: 10
    match_chroma_phase: true
  - node_id: "node_2"
    stage_name: "Passthrough"
    x_position: 550.00
    y_position: 150.00

edges:
  - source: "START"
    target: "node_1"
  - source: "node_1"
    target: "node_2"

    action: "add"
    notes: "Tape damage - line 1 of 3"
  
  - field_id: 250
    line: 121
    start_sample: 300
    end_sample: 400
    action: "add"
    notes: "Tape damage - line 2 of 3"
  
  - field_id: 250
    line: 122
    start_sample: 300
    end_sample: 400
    action: "add"
    notes: "Tape damage - line 3 of 3"

# Stages transform video signals (produce new representations)
stages:
  - type: dropout_correct
    enabled: true
    
    # Correction parameters (compatible with ld-dropout-correct)
    
    # Extend detected dropouts by N samples (0-24)
    # Use 24 for heavily damaged sources (overcorrect mode)
    overcorrect_extension: 0
    
    # Only use lines from the same field for correction
    # Set to true to avoid field blending artifacts
    intrafield_only: false
    
    # Use second field first instead of first field first
    # Rarely needed, for non-standard field ordering
    reverse_field_order: false
    
    # Maximum number of lines to search for replacement (1-10)
    # Larger values find better matches but are slower
    max_replacement_distance: 10
    
    # Match chroma phase when selecting replacement lines
    # Set to false for B&W content or when color isn't critical
    match_chroma_phase: true
