name: "NTSC Stacking Composite DO 2"
description: "NTSC LaserDisc composite with dropouts only for stacking testing - Disc 2"

output:
  filename: "${ENCODE_ORC_OUTPUT_ROOT}/stacking/ntsc-stacking-comp-2-do"
  format: "ntsc-composite"

laserdisc:
  mode: "cav"

pipeline:
  preprocessing:
    filters:
      chroma:
        enabled: true
  
  metadata:
    generators:
      - type: "biphase-vbi"
        enabled: true
        lines: [16, 17, 18, 278, 279, 280]
        format: "picture-number"
      
      - type: "vits-ntsc"
        enabled: true
        signals:
          - line: 13
            signal: "ntc7-composite"
          - line: 19
            signal: "vir"
          - line: 275
            signal: "ntc7-combination"
          - line: 281
            signal: "vir"
          
      
      - type: "color-burst"
        enabled: true

  effects:
    # Random dropouts to simulate disc damage and scratches
    - type: "dropout"
      enabled: true
      density: 0.001
      multi_field_probability: 0.30    # 30% chance of multi-field (scratches)
      single_field_probability: 0.70   # 70% chance of single-field (disc degradation)
      seed: 22

sections:
  - name: "Test Content"
    duration: 10
    source:
      type: "yuv422-image"
      file: "${ENCODE_ORC_ASSETS}/ntsc-raw/525_5994_75_BARS.raw"
    biphase-vbi:
      disc_area: "programme-area"
      picture_start: 1
  
  - name: "Test Content"
    duration: 10
    source:
      type: "yuv422-image"
      file: "${ENCODE_ORC_ASSETS}/ntsc-raw/525_5994_CHROMA_RAMP.raw"
    biphase-vbi:
      disc_area: "programme-area"
  
  - name: "Test Content"
    duration: 30
    source:
      type: "mp4-file"
      file: "${ENCODE_ORC_ASSETS}/ntsc-mp4/ntsc-ice-skating.mp4"
    biphase-vbi:
      disc_area: "programme-area"
