# Heavily Damaged Source - Overcorrect Mode
# Use this configuration for LaserDiscs with severe dropout issues
# Extends all detected dropouts aggressively for better visual quality

name: "Overcorrect Mode for Damaged Sources"
version: "1.0"

observers:
  - type: biphase
    enabled: true
  
  - type: vits
    enabled: true

# For severely damaged sources, uses TBC hints from decoder, you may want to add decisions
# to remove entire fields or mark large damaged regions
dropout_decisions:
  # Example: Mark entire visible area of a damaged field
  - field_id: 1000
    line: 50
    start_sample: 0
    end_sample: 1900
    action: "add"
    notes: "Entire field corrupted by disc rot"

stages:
  - type: dropout_correct
    enabled: true
    
    # OVERCORRECT MODE: Extend dropouts by 24 samples
    # This aggressively corrects dropouts, useful for heavily damaged sources
    overcorrect_extension: 24
    
    # Allow interfield correction for best results
    intrafield_only: false
    
    reverse_field_order: false
    
    # Search up to 10 lines for good replacement data
    max_replacement_distance: 10
    
    match_chroma_phase: true
