name: "PAL Stacking Y/C 3"
description: "PAL LaserDisc Y/C with noise only for stacking testing - Disc 3"

output:
  filename: "../../encode-output/stacking/pal-stacking-yc-3"
  format: "pal-yc"

laserdisc:
  mode: "cav"

pipeline:
  preprocessing:
    filters:
      chroma:
        enabled: true
  
  metadata:
    generators:
      - type: "biphase-vbi"
        enabled: true
        lines: [16, 17, 18, 328, 329, 330]
        format: "picture-number"
      
      - type: "vits-pal"
        enabled: true
        signals:
          - line: 13
            signal: "multiburst"
          - line: 19
            signal: "uk-national"
          - line: 325
            signal: "itu-combination"
          - line: 331
            signal: "itu-composite"
      
      - type: "color-burst"
        enabled: true

  effects:
    # Gaussian noise to simulate disc degradation
    - type: "noise"
      enabled: true
      snr_db: 20.0  # Signal-to-noise ratio in dB
      seed: 23      # For reproducible results

sections:
  - name: "Test Content"
    duration: 10
    source:
      type: "yuv422-image"
      file: "../../external/encode-orc/testcard-images/pal-raw/625_50_75_BARS.raw"
    biphase-vbi:
      disc_area: "programme-area"
      picture_start: 1
  
  - name: "Test Content"
    duration: 10
    source:
      type: "yuv422-image"
      file: "../../external/encode-orc/testcard-images/pal-raw/625_50_CHROMA_RAMP.raw"
      disc_area: "programme-area"
  
  - name: "Test Content"
    duration: 30
    source:
      type: "mp4-file"
      file: "../../external/encode-orc/testcard-images/pal-mp4/pal-ice-skating.mp4"
    biphase-vbi:
      disc_area: "programme-area"
