name: "NTSC with 25 dB SNR"
description: "NTSC LaserDisc with CAV picture numbering (IEC 60856-1986)"

output:
  filename: "../../encode-output/generic/ntsc-cav-snr-25"
  format: "ntsc-composite"

laserdisc:
  mode: "cav"

pipeline:
  preprocessing:
    filters:
      chroma:
        enabled: true
  
  metadata:
    generators:
      - type: "biphase-vbi"
        enabled: true
        lines: [16, 17, 18, 278, 279, 280]
        format: "picture-number"
      
      - type: "vits-ntsc"
        enabled: true
        signals:
          - line: 13
            signal: "ntc7-composite"
          - line: 19
            signal: "vir"
          - line: 275
            signal: "ntc7-combination"
          - line: 281
            signal: "vir"
          
      
      - type: "color-burst"
        enabled: true

  effects:
    # Gaussian noise to simulate disc degradation
    - type: "noise"
      enabled: true
      snr_db: 25.0  # Signal-to-noise ratio in dB
      seed: 42      # For reproducible results

sections:
  - name: "Lead-in"
    duration: 1
    source:
      type: "yuv422-image"
      file: "../../external/encode-orc/testcard-images/ntsc-raw/525_5994_75_BARS.raw"
    biphase-vbi:
      disc_area: "lead-in"
  
  - name: "Test Content"
    duration: 20
    source:
      type: "yuv422-image"
      file: "../../external/encode-orc/testcard-images/ntsc-raw/525_5994_75_BARS.raw"
    biphase-vbi:
      disc_area: "programme-area"
      picture_start: 1
  
  - name: "Lead-out"
    duration: 1
    source:
      type: "yuv422-image"
      file: "../../external/encode-orc/testcard-images/ntsc-raw/525_5994_75_BARS.raw"
    biphase-vbi:
      disc_area: "lead-out"
