name: "NTSC YC Dropout Correction Test"
description: "NTSC YC test signal with line dropouts for DOC testing"

output:
  filename: "../../encode-output/dropout-correction/ntsc-yc-docorr-test"
  format: "ntsc-yc"

laserdisc:
  mode: "cav"

pipeline:
  preprocessing:
    filters:
      chroma:
        enabled: true
  
  metadata:
    generators:
      - type: "biphase-vbi"
        enabled: true
        lines: [16, 17, 18, 278, 279, 280]
        format: "picture-number"
      
      - type: "vits-ntsc"
        enabled: true
        signals:
          - line: 13
            signal: "ntc7-composite"
          - line: 19
            signal: "vir"
          - line: 275
            signal: "ntc7-combination"
          - line: 281
            signal: "vir"
      
      - type: "color-burst"
        enabled: true
  
  effects:  
    # Random dropouts to simulate disc damage and scratches
    - type: "dropout"
      enabled: true
      density: 0.001
      multi_field_probability: 0.30    # 30% chance of multi-field (scratches)
      single_field_probability: 0.70   # 70% chance of single-field (disc degradation)
      seed: 66

sections:
  - name: "Test bars"
    duration: 20
    source:
      type: "yuv422-image"
      file: "../../external/encode-orc/testcard-images/ntsc-raw/525_5994_75_BARS.raw"
    biphase-vbi:
      disc_area: "programme-area"
      picture_start: 1